dishwasher:
  manufacturer: Miele
  model: G 470
  hardware:
    outputs:
      relayPinMain: 17
      relayPinLED: 27
      relayPinP9: 22
      relayPinP7: 10
      relayPinP6: 9
      relayPinP4: 11
      relayPinMotor: 19
      relayPinSummer: 26
    inputs:
      sensorPinP4: 23
      sensorPinP6: 24
      sensorPinP7: 25
      sensorPinP9: 8
      sensorPinP10: 7
      sensorPinP11: 12
      sensorPinP12: 16
      sensorPinMotor: 18
      sensorPinUmwelz: 21
      sensorPinEinlauf: 13
      sensorPinAblauf: 6
      sensorPinHeizen: 5
    addresses:
      sesorTemp: 28-0000058f94d2
  software:
    loopSleepTime: 1
    backendBaseUrl: 'http://mielesmart.de/back'
    loggingDirectory: /home/pi/MieleGSmart/Firmware/logs/
    sendProcessDataRepeatedTimerInterval: 1
    programTargetTemps:
      targetTemp66: 56
      targetTemp56: 47
      targetTemp45: 35
      tempGrowthSpeed: 0.043 #Grad Celsius pro Sekunde
